pub mod flags;
pub mod load_store;
pub mod arithmetic;
pub mod bitwise;
pub mod shifts;
pub mod stack;
pub mod branching;
pub mod jumps;
pub mod transfer;
pub mod increment_decrement;
pub mod system;

pub use system::{NOP};
pub use increment_decrement::{/* INC, DEC, */ INX, DEX, INY, DEY};
pub use transfer::{TAX, TAY, TXA, TYA};
pub use jumps::{/* JMP, */ JSR, RTS};
pub use branching::{BEQ,  BNE, BCS, BCC, BMI, BPL, BVC, BVS };
pub use stack::{TSX, TXS};
pub use bitwise::{AND, ORA, EOR, BIT};
pub use arithmetic::{ADC, CMP, CPX, CPY, SBC};
pub use flags::{CLC, CLD, CLI, CLV, SEI};
pub use load_store::{LDA, LDX, LDY, STA, STX, STY};