[package]
name = "nes_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
once_cell = "1.18"
paste = "1.0"
bitflags = "2.8.0"

[profile.dev]
opt-level = 0 # Ensure no optimization for debugging