[package]
name = "nes_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
once_cell = "1.18"
paste = "1.0"
bitflags = "2.8.0"

[profile.dev]
<<<<<<< HEAD
opt-level = 0            # Ensure no optimizations
debug = true             # Include debug symbols
debug-assertions = true  # Keep debug assertions
overflow-checks = true   # Keep overflow checks

=======
opt-level = 0 # Ensure no optimization for debugging
>>>>>>> parent of 9ef4987 (feat: Added PPU support)
